### ISSUE TITLE
右侧编辑器样式错乱

### ISSUE THREAD

**Issue by rhwoodpecker** [SK-Luffa/file-explorer#7]
问题：
1. 下方code内容顶到文件名列表
2. 文件名列表太长换行样式错乱
3. 文件名列表不会横向滚动

<img width="802" alt="image" src="https://user-images.githubusercontent.com/22131908/223674140-a12f1677-d387-4389-8d02-e6aa07a00140.png">

#8

**Comment by LsyWeb** [comment]
感谢提出问题
